import React from "react"
import { useState } from 'react';
import Alexandria from "../components/Alexandria";
import Alsharqiya from "../components/Alsharqiya";
import Aswan from "../components/Aswan";
import Assuit from "../components/Assuit";
import Beheira from "../components/Beheira";
import Benisuef from "../components/Benisuef";
import Cairo from "../components/Cairo";
import Dakahlia from "../components/Dakahlia";
import Damietta from "../components/Damietta";
import Fayoum from "../components/Fayoum";
import Gharbia from "../components/Gharbia";
import Giza from "../components/Giza";
import Ismailia from "../components/Ismailia";
import Kafr from "../components/Kafr";
import Matrouh from "../components/Matrouh";
import Minya from "../components/Minya";
import Menofia from "../components/Menofia";
import Northsinai from "../components/Northsinai";
import Portsaid from "../components/Portsaid";
import Qualyubia from "../components/Qualyubia";
import Qena from "../components/Qena";
import Redsea from "../components/Redsea";
import Sohag from "../components/Sohag";
import Southsinai from "../components/Southsinai";
import Suez from "../components/Suez";
import Luxor from "../components/Luxor";
import Newvalley from "../components/Newvalley";

const Explore = () => {

    const [alexandria, setAlexandria] = useState(true)
    const [aswan, setAswan] = useState(false)
    const [alsharqiya, setAlsharqiya] = useState(false)
    const [assuit, setAssuit] = useState(false)
    const [beheira, setBeheira] = useState(false)
    const [benisuef, setBenisuef] = useState(false)
    const [cairo, setCairo] = useState(false)
    const [dakahlia, setDakahlia] = useState(false)
    const [damietta, setDamietta] = useState(false)
    const [fayoum, setFayoum] = useState(false)
    const [gharbia, setGharbia] = useState(false)
    const [giza, setGiza] = useState(false)
    const [ismailia, setIsmailia] = useState(false)
    const [kafr, setKafr] = useState(false)
    const [matrouh, setMatrouh] = useState(false)
    const [minya, setMinya] = useState(false)
    const [menofia, setMenofia] = useState(false)
    const [newvalley, setNewvalley] = useState(false)
    const [northsinai, setNorthsinai] = useState(false)
    const [portsaid, setPortsaid] = useState(false)
    const [qualyubia, setQualyubia] = useState(false)
    const [qena, setQena] = useState(false)
    const [redsea, setRedsea] = useState(false)
    const [sohag, setSohag] = useState(false)
    const [southsinai, setSouthsinai] = useState(false)
    const [suez, setSuez] = useState(false)
    const [luxor, setLuxor] = useState(false)

    const alexandriaToggle = () => {
        setAlexandria(true)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const aswanToggle = () => {
        setAlexandria(false)
        setAswan(true)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const alsharqiyaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(true)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const assuitToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(true)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const beheiraToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(true)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const benisuefToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(true)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const cairoToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(true)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const dakahliaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(true)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const damiettaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(true)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const fayoumToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(true)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const gharbiaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(true)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const gizaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(true)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const ismailiaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(true)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

     const kafrToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(true)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const matrouhToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(true)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const minyaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(true)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const menofiaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(true)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const newvalleyToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(true)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const northsinaiToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(true)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const portsaidToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(true)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const qualyubiaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(true)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const qenaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(true)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

     const redseaToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(true)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const sohagToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(true)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(false)
    }

    const southsinaiToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(true)
        setSuez(false)
        setLuxor(false)
    }

    const suezToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(true)
        setLuxor(false)
    }

    const luxorToggle = () => {
        setAlexandria(false)
        setAswan(false)
        setAlsharqiya(false)
        setAssuit(false)
        setBeheira(false)
        setBenisuef(false)
        setCairo(false)
        setDakahlia(false)
        setDamietta(false)
        setFayoum(false)
        setGharbia(false)
        setGiza(false)
        setIsmailia(false)
        setKafr(false)
        setMatrouh(false)
        setMinya(false)
        setMenofia(false)
        setNewvalley(false)
        setNorthsinai(false)
        setPortsaid(false)
        setQualyubia(false)
        setQena(false)
        setRedsea(false)
        setSohag(false)
        setSouthsinai(false)
        setSuez(false)
        setLuxor(true)
    }
    return (
        <>
            <h1 className="header">Explore Egypt</h1>
            <div className="container">
                <div className="govs">
                    {alexandria ? <Alexandria /> : null}
                    {alsharqiya ? <Alsharqiya /> : null}
                    {aswan ? <Aswan /> : null}
                    {assuit ? <Assuit /> : null}
                    {beheira ? <Beheira /> : null}
                    {benisuef ? <Benisuef /> : null}
                    {cairo ? <Cairo /> : null}
                    {dakahlia ? <Dakahlia /> : null}
                    {damietta ? <Damietta /> : null}
                    {fayoum ? <Fayoum /> : null}
                    {gharbia ? <Gharbia /> : null}
                    {giza ? <Giza /> : null}
                    {ismailia ? <Ismailia /> : null}
                    {kafr ? <Kafr /> : null}
                    {matrouh ? <Matrouh /> : null}
                    {minya ? <Minya /> : null}
                    {menofia ? <Menofia /> : null}
                    {newvalley ? <Newvalley /> : null}
                    {northsinai ? <Northsinai /> : null}
                    {portsaid ? <Portsaid /> : null}
                    {qualyubia ? <Qualyubia /> : null}
                    {qena ? <Qena /> : null}
                    {redsea ? <Redsea /> : null}
                    {sohag ? <Sohag /> : null}
                    {southsinai ? <Southsinai /> : null}
                    {suez ? <Suez /> : null}
                    {luxor ? <Luxor /> : null}
                </div>
           
            <div className="side-panel">
                <ul>
                    <a href="#" onClick={alexandriaToggle}><li className="side">Alexandria</li></a>
                    <a href="#" onClick={alsharqiyaToggle}><li className="side">Al-Sharqia</li></a>
                    <a href="#" onClick={assuitToggle}><li className="side">Assuit</li></a>
                    <a href="#" onClick={aswanToggle}><li className="side">Aswan</li></a>
                    <a href="#" onClick={beheiraToggle}><li className="side">Beheira</li></a>
                    <a href="#" onClick={benisuefToggle}><li className="side">Beni Suef</li></a>
                    <a href="#" onClick={cairoToggle}><li className="side">Cairo</li></a>
                    <a href="#" onClick={dakahliaToggle}><li className="side">Dakahlia</li></a>
                    <a href="#" onClick={damiettaToggle}><li className="side">Damietta</li></a>
                    <a href="#" onClick={fayoumToggle}><li className="side">Fayoum</li></a>
                    <a href="#" onClick={gharbiaToggle}><li className="side">Gharbia</li></a>
                    <a href="#" onClick={gizaToggle}><li className="side">Giza</li></a>
                    <a href="#" onClick={ismailiaToggle}><li className="side">Ismailia</li></a>
                    <a href="#" onClick={kafrToggle}><li className="side">Kafr El-Sheikh</li></a>
                    <a href="#" onClick={luxorToggle}><li className="side">Luxor</li></a>
                    <a href="#" onClick={matrouhToggle}><li className="side">Matrouh</li></a>
                    <a href="#" onClick={menofiaToggle}><li className="side">Menofia</li></a>
                    <a href="#" onClick={minyaToggle}><li className="side">Minya</li></a>
                    <a href="#" onClick={newvalleyToggle}><li className="side">New Valley</li></a>
                    <a href="#" onClick={northsinaiToggle}><li className="side">North Sinai</li></a>
                    <a href="#" onClick={portsaidToggle}><li className="side">Port Said</li></a>
                    <a href="#" onClick={qenaToggle}><li className="side">Qena</li></a>
                    <a href="#" onClick={qualyubiaToggle}><li className="side">Qualyubia</li></a>
                    <a href="#" onClick={redseaToggle}><li className="side">Red Sea</li></a>
                    <a href="#" onClick={sohagToggle}><li className="side">Sohag</li></a>
                    <a href="#" onClick={southsinaiToggle}><li className="side">South Sinai</li></a>
                    <a href="#" onClick={suezToggle}><li className="side">Suez</li></a>

                </ul>
            </div>
            </div>
        </>
    )
}

export default Explore